<?php
/*
 * Copyright (c) 2020 PayGate (Pty) Ltd
 *
 * Author: App Inlet (Pty) Ltd
 *
 * Released under the GNU General Public License
 */
$methodCode = Mage::getSingleton( 'checkout/session' )->getQuote()->getPayment()->getMethod();
if ( $methodCode == 'sid' ) {
    $baseURL = Mage::getBaseUrl();
    ?>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery(".btn-checkout").attr( "OnClick", "createSidOrder('<?php echo $baseURL ?>');" );
        });
    </script>
    <?php
}
?>